import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { ToasterProvider } from "@/components/toaster-provider";
import { AuthProvider } from "@/contexts/auth-context";
import { cn } from "@/lib/utils";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head />
      <body className={cn(
        inter.variable,
        "min-h-screen bg-background font-sans antialiased",
        "transition-colors duration-150",
        "bg-white dark:bg-neutral-950",
        "text-neutral-950 dark:text-neutral-50"
      )}>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <AuthProvider>
              {children}
              <ToasterProvider />
            </AuthProvider>
          </ThemeProvider>
      </body>
    </html>
  );
}
